FROM alpine:latest
MAINTAINER Samuel "dgellow" El-Borai <samuel.elborai@gmail.com>

ENV BUILD_COMMAND "ls"
ENV BUILD_DIR "."

WORKDIR /build
RUN apk update &&\
    apk add ca-certificates &&\
    update-ca-certificates &&\
    apk add wget git &&\
    wget -q https://dl.minio.io/client/mc/release/linux-amd64/mc &&\
    chmod +x mc
ADD ./scripts/static_build_push.sh /build/build_push.sh

ENTRYPOINT ["sh", "/build/build_push.sh"]
